set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
set relativenumber
set number
set autoread

" Why on earth would I want modelines to work?
set modelines=0

" Vundle
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Plugins here
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'Quramy/tsuquyomi'
Plugin 'itchyny/lightline.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'ternjs/tern_for_vim'
Plugin 'tpope/vim-surround'
Plugin 'prettier/vim-prettier'

call vundle#end()

" Use ripgrep if present
if executable("rg")
  set grepprg=rg\ --vimgrep\ --no-heading
  set grepformat=%f:%l:%c:%m,%f:%l:%m
endif

filetype plugin indent on
filetype plugin on
syntax enable
set term=xterm-256color
set omnifunc=syntaxcomplete#Complete

" Leader key
let mapleader=","

" Make jj switch to normal mode
inoremap jj <Esc>

" Make ,w save and write in insert mode
inoremap <leader>w <Esc>:wa<CR>

" Changes to navigating vim splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
tnoremap <C-J> <C-W><C-J>
tnoremap <C-K> <C-W><C-K>
tnoremap <C-L> <C-W><C-L>
tnoremap <C-H> <C-W><C-H>
set splitbelow
set splitright

noremap gh /'\<Bar>"\<Bar>(\<Bar>)\<Bar>\[\<Bar>\]\<Bar>{\<Bar>}\<Bar>\.\<Bar>,<CR>

nnoremap <C-tab> :bnext

" NERDTree toggle
nnoremap <C-e> :NERDTree<CR>
nnoremap <leader>f :NERDTreeFocus<CR>

" Shortcuts for splits
noremap <leader>v :vsplit<CR>
noremap <leader>h :split<CR>

" Shortcut for write/quit
noremap <leader>q :q<CR>
noremap <leader>w :wa<CR>

" Fugitive shortcuts
noremap <leader>gs :Gstatus<CR>
noremap <leader>gi :Gdiff<CR>
noremap <leader>gc :Gcommit -m "

" Make CtrlP work with ctrl-p
nnoremap <C-p> :CtrlP<CR>
" Make CtrlP use .gitignore file
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
" Make CtrlP always use vim working directory
let g:ctrlp_working_path_mode = 0

" Remove trailing whitespace
autocmd BufWritePre * if &buftype != 'terminal' | :%s/\s\+$//e | endif

" Built-in file explorer settings
let g:netrw_winsize = 25
let g:netrw_banner = 0
let g:netrw_liststyle = 3

" Prettier plugin settings
let g:prettier#quickfix_enabled = 0
let g:prettier#autoformat = 0
autocmd BufWritePre *.ts PrettierAsync

" TypeScript (tsuquyomi) settings
" set <F12>=<C-v><F12>
autocmd FileType typescript noremap <F12> :TsuquyomiDefinition<CR>
autocmd FileType javascript noremap <F12> :TernDef<CR>
autocmd FileType typescript noremap <F2> :TsuRenameSymbol<CR>
autocmd FileType javascript noremap <F2> :TernRename<CR>
inoremap <leader>, <C-x><C-o>
autocmd FileType typescript nmap <buffer> <leader>t : <C-u>echo tsuquyomi#hint()<CR>
autocmd FileType javascript nmap <buffer> <leader>t :TernType<CR>

" Tab settings
set expandtab
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent

" Fix OSX backspace issues
set backspace=indent,eol,start
set noshowmode

" Disable line numbers in terminal mode
autocmd BufWinEnter * if &buftype == 'terminal' | setlocal norelativenumber | setlocal nonumber | endif
" Shortcut for running tests in current terminal window
nnoremap <leader>yt :term ++curwin yarn test<CR>
" Quickly open window suitable for terminal
nnoremap <leader>ot :botright :new<CR>:setlocal winfixheight<CR>

" Quickly jump to previous buffer
noremap <leader>p :b#<CR>

" Navigate lgrep search results
nnoremap <leader>n :lnext<CR>
nnoremap <leader>N :lprevious<CR>
colorscheme current
