set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
set relativenumber
set number
set autowriteall
set autoread

" Vundle
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Plugins here
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'leafgarland/typescript-vim'
" Plugin 'jiangmiao/auto-pairs'
Plugin 'Quramy/tsuquyomi'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'tpope/vim-fugitive'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'ternjs/tern_for_vim'
Plugin 'tpope/vim-surround'
" Maybe just use :b <tab> instead Plugin 'jlanzarotta/bufexplorer'

call vundle#end()
filetype plugin indent on
filetype plugin on
syntax enable
set term=xterm-256color
set omnifunc=syntaxcomplete#Complete

" Leader key
let mapleader=","

" Make jj switch to normal mode 
inoremap jj <Esc>

" Rebind arrow keys
noremap j <left>
noremap k <down>
noremap l <up>
noremap ; <right>
noremap h ;

nnoremap <C-tab> :bnext

" NERDTree toggle
nnoremap <C-e> :NERDTree<CR>
nnoremap <leader>f :NERDTreeFocus<CR>

" Shortcuts for splits
noremap <leader>v :vsplit<CR>
noremap <leader>h :split<CR>

" Shortcut for quit
noremap <leader>q :q<CR>

" Make CtrlP work with ctrl-p
nnoremap <C-p> :CtrlP<CR>
" Make CtrlP use .gitignore file
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']

" Built-in file explorer settings
let g:netrw_winsize = 25
let g:netrw_banner = 0
let g:netrw_liststyle = 3

" TypeScript (tsuquyomi) settings
" set <F12>=<C-v><F12>
autocmd FileType typescript noremap <F12> :TsuquyomiDefinition<CR>
autocmd FileType javascript noremap <F12> :TernDef<CR>
autocmd FileType typescript noremap <F2> :TsuRenameSymbol<CR>
autocmd FileType javascript noremap <F2> :TernRename<CR>
inoremap <leader>, <C-x><C-o>
autocmd FileType typescript nmap <buffer> <leader>t : <C-u>echo tsuquyomi#hint()<CR>
autocmd FileType javascript nmap <buffer> <leader>t :TernType<CR>

" Tab settings
set expandtab
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent

" Activate airline immediately: https://github.com/vim-airline/vim-airline/wiki/FAQ
set laststatus=2
" Add powerline font symbols
let g:airline_powerline_fonts=1
" Disable default mode since airline shows it to us anyways

" Fix OSX backspace issues
set backspace=indent,eol,start
set noshowmode

colorscheme current

" Add cursorline
" augroup CursorLine
"   au!
"   au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
"   au WinLeave * setlocal nocursorline
" augroup END
" hi CursorLine cterm=NONE ctermbg=darkgray ctermfg=white guibg=darkgray guifg=white
